# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: file_processor.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'file_processor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x66ile_processor.proto\x12\x0e\x66ile_processor\"V\n\tFileChunk\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\x12\x0f\n\x07success\x18\x03 \x01(\x08\x12\x15\n\ris_last_chunk\x18\x04 \x01(\x08\"3\n\x12ResizeImageRequest\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\"\x9a\x01\n\x12ImageStreamRequest\x12\x10\n\x06\x66ormat\x18\x01 \x01(\tH\x00\x12\x36\n\x08metadata\x18\x02 \x01(\x0b\x32\".file_processor.ResizeImageRequestH\x00\x12*\n\x05\x63hunk\x18\x03 \x01(\x0b\x32\x19.file_processor.FileChunkH\x00\x42\x0e\n\x0crequest_type2\xd4\x02\n\x14\x46ileProcessorService\x12G\n\x0b\x43ompressPDF\x12\x19.file_processor.FileChunk\x1a\x19.file_processor.FileChunk(\x01\x30\x01\x12H\n\x0c\x43onvertToTXT\x12\x19.file_processor.FileChunk\x1a\x19.file_processor.FileChunk(\x01\x30\x01\x12W\n\x12\x43onvertImageFormat\x12\".file_processor.ImageStreamRequest\x1a\x19.file_processor.FileChunk(\x01\x30\x01\x12P\n\x0bResizeImage\x12\".file_processor.ImageStreamRequest\x1a\x19.file_processor.FileChunk(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'file_processor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FILECHUNK']._serialized_start=40
  _globals['_FILECHUNK']._serialized_end=126
  _globals['_RESIZEIMAGEREQUEST']._serialized_start=128
  _globals['_RESIZEIMAGEREQUEST']._serialized_end=179
  _globals['_IMAGESTREAMREQUEST']._serialized_start=182
  _globals['_IMAGESTREAMREQUEST']._serialized_end=336
  _globals['_FILEPROCESSORSERVICE']._serialized_start=339
  _globals['_FILEPROCESSORSERVICE']._serialized_end=679
# @@protoc_insertion_point(module_scope)
